module.exports = {
  up: `CREATE TABLE STOCK_DATA_INFO (
    STOCK_ID CHAR(32) PRIMARY KEY,
    DATA_TIMESTAMP TIMESTAMP,
    OPENING FLOAT,
    CLOSING FLOAT,
    HIGHEST FLOAT,
    LOWEST FLOAT,
    VOLUME FLOAT
);`,
  down: `DROP TABLE STOCK_DATA_INFO;`,
};
